name: richmond-api
services:
  richmond-api:
    image: ghcr.io/akorzunin/richmond-api:${IMAGE_TAG}
    container_name: richmond-api
    restart: unless-stopped
    ports:
      - "9902:8080"
    depends_on:
      - postgres
      - rustfs
    environment:
      - PG_ADDRESS=postgres:5432
      - PG_USER=${AUTH_USER}
      - PG_PASS=${AUTH_PASS}
      - S3_ADDRESS=rustfs:9000
      - S3_ACCESS_KEY=${AUTH_USER}
      - S3_SECRET_KEY=${AUTH_PASS}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.83
    container_name: richmond-rustfs
    restart: unless-stopped
    user: root
    environment:
      - RUSTFS_ACCESS_KEY=${AUTH_USER}
      - RUSTFS_SECRET_KEY=${AUTH_PASS}
    ports:
      - "9900:9000"
      - "9901:9001"
    volumes:
      - ${DATA_DIR:-/mnt/storage/richmond/rustfs/data}:/data
      - ${DATA_DIR:-/mnt/storage/richmond/rustfs/logs}:/logs
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M

  postgres:
    image: postgres:18-alpine
    container_name: richmond-postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${AUTH_USER}
      - POSTGRES_PASSWORD=${AUTH_PASS}
      - POSTGRES_DB=main
    ports:
      - "9903:5432"
    volumes:
      - ${DATA_DIR:-/mnt/storage/richmond/postgres}:/var/lib/postgresql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
