// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCat = `-- name: CreateCat :one
INSERT INTO cats (user_id, name, birth_date, breed, weight, habits)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING cat_id, user_id, name, birth_date, breed, weight, habits, created_at, updated_at
`

type CreateCatParams struct {
	UserID    int32       `json:"user_id"`
	Name      string      `json:"name"`
	BirthDate pgtype.Date `json:"birth_date"`
	Breed     string      `json:"breed"`
	Weight    float64     `json:"weight"`
	Habits    string      `json:"habits"`
}

func (q *Queries) CreateCat(ctx context.Context, arg CreateCatParams) (Cat, error) {
	row := q.db.QueryRow(ctx, createCat,
		arg.UserID,
		arg.Name,
		arg.BirthDate,
		arg.Breed,
		arg.Weight,
		arg.Habits,
	)
	var i Cat
	err := row.Scan(
		&i.CatID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.Breed,
		&i.Weight,
		&i.Habits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatByID = `-- name: GetCatByID :one
SELECT cat_id, user_id, name, birth_date, breed, weight, habits, created_at, updated_at FROM cats WHERE cat_id = $1
`

func (q *Queries) GetCatByID(ctx context.Context, catID int32) (Cat, error) {
	row := q.db.QueryRow(ctx, getCatByID, catID)
	var i Cat
	err := row.Scan(
		&i.CatID,
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.Breed,
		&i.Weight,
		&i.Habits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
