// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (user_id, cat_id, post_id, key, url, width, height, size, quality, type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, cat_id, post_id, key, url, width, height, size, quality, type, created_at, updated_at
`

type CreateFileParams struct {
	UserID  int32       `json:"user_id"`
	CatID   pgtype.Int4 `json:"cat_id"`
	PostID  pgtype.Int4 `json:"post_id"`
	Key     string      `json:"key"`
	Url     string      `json:"url"`
	Width   int32       `json:"width"`
	Height  int32       `json:"height"`
	Size    int64       `json:"size"`
	Quality string      `json:"quality"`
	Type    string      `json:"type"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.CatID,
		arg.PostID,
		arg.Key,
		arg.Url,
		arg.Width,
		arg.Height,
		arg.Size,
		arg.Quality,
		arg.Type,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatID,
		&i.PostID,
		&i.Key,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Quality,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, cat_id, post_id, key, url, width, height, size, quality, type, created_at, updated_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatID,
		&i.PostID,
		&i.Key,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Quality,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
