// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type User struct {
	UserID   int32  `json:"user_id"`
	UserName string `json:"user_name"`
	UserPass string `json:"user_pass"`
}
