// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, cat_id, title, body)
VALUES ($1, $2, $3, $4)
RETURNING post_id, user_id, cat_id, title, body, created_at, updated_at
`

type CreatePostParams struct {
	UserID int32  `json:"user_id"`
	CatID  int32  `json:"cat_id"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.CatID,
		arg.Title,
		arg.Body,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.CatID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT post_id, user_id, cat_id, title, body, created_at, updated_at FROM posts WHERE post_id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, postID int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, postID)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.CatID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
