// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, user_pass)
VALUES ($1, $2)
RETURNING user_id, user_name, user_pass
`

type CreateUserParams struct {
	UserName string `json:"user_name"`
	UserPass string `json:"user_pass"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserName, arg.UserPass)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPass)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_name, user_pass FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPass)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT user_id, user_name, user_pass FROM users WHERE user_name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, userName)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPass)
	return i, err
}
